rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3

script: "bundle exec rake test"

notifications:
  disabled: true

before_install:
  - "sudo add-apt-repository ppa:gijzelaar/opencv2.3"
  - "sudo apt-get -qq update"
  - "sudo apt-get -q install libcv-dev=2.3.1-1 libopencv-dev=2.3.1-1"
